---
- hosts: 'rsync_ihep'
  vars:
      WARDER_DIR: /home/treskov/rsync_warden
      WARDER_CLIENTS:
          - "warden_client@1.service"
          - "warden_client@2.service"
  tasks:
      - name: Copy rsync client conf to systemd
        copy:
            remote_src: yes
            src: '{{ WARDER_DIR }}/systemd/warden_client@.service'
            dest: '/etc/systemd/system/warden_client@.service'

      - name: Enable clients if neccessary
        systemd:
            name: "{{ item }}"
            enabled: yes
        loop: "{{ WARDER_CLIENTS }}"

      - name: Stop clients if running
        systemd:
            name: "{{ item }}"
            state: stopped
        loop: "{{ WARDER_CLIENTS }}"
        tags: ['stop']

      - name: Force config reload
        systemd: 
            daemon_reload: yes

      - name: Start clients
        systemd:
            name: "{{ item }}"
            state: started
            daemon_reload: yes
        loop: "{{ WARDER_CLIENTS }}"
        tags: ['start']
