---
- hosts: 'rsync_ihep'
  vars:
      WARDER_DIR: /home/treskov/rsync_warden
  tasks:
      - name: Allow connections to warden server
        ufw:
          rule: allow
          port: 8000 
          proto: tcp
          src: 159.93.221.84

      - name: Copy rsync server conf to systemd
        copy:
            remote_src: yes
            src: '{{ WARDER_DIR }}/systemd/warden_client@.service'
            dest: /etc/systemd/system/warden_client.service
      - name: Force config reload
        systemd: 
            daemon_reload: yes

      - debug: 
            msg: "Now go to host and start clients by hands!"

